//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTools.Linter.CommandLine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamTools.Linter.CommandLine.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong command-line arguments. Use --help to see valid arguments..
        /// </summary>
        internal static string AppErrors_bad_cli_argument {
            get {
                return ResourceManager.GetString("AppErrors_bad_cli_argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins to load or invalid config format. Doing nothing.
        /// </summary>
        internal static string AppErrors_bad_config {
            get {
                return ResourceManager.GetString("AppErrors_bad_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dumping result....
        /// </summary>
        internal static string AppMessages_dumping_result {
            get {
                return ResourceManager.GetString("AppMessages_dumping_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished in {0}.
        /// </summary>
        internal static string AppMessages_finished_in_time {
            get {
                return ResourceManager.GetString("AppMessages_finished_in_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading config from {0}.
        /// </summary>
        internal static string AppMessages_loading_config {
            get {
                return ResourceManager.GetString("AppMessages_loading_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No plugins loaded. Doing nothing.
        /// </summary>
        internal static string AppMessages_no_plugins {
            get {
                return ResourceManager.GetString("AppMessages_no_plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed with exception:.
        /// </summary>
        internal static string AppMessages_run_failed {
            get {
                return ResourceManager.GetString("AppMessages_run_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violations: {0}.
        /// </summary>
        internal static string AppMessages_total_violations {
            get {
                return ResourceManager.GetString("AppMessages_total_violations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string AppMessages_version_info {
            get {
                return ResourceManager.GetString("AppMessages_version_info", resourceCulture);
            }
        }
    }
}
